---

services:
  bind9:
    profiles: [1-infra]
    container_name: bind9-dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/Chicago
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind9/config:/etc/bind
      - ./bind9/cache:/var/cache/bind
      - ./bind9/records:/var/lib/bind
    restart: unless-stopped
